// frontend/src/pages/PaperDetailPage.tsx
import React, { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import TrendChart from '../components/TrendChart'
import { papersService, PaperDetail, MetricSnapshot } from '../services/papersService'

const PaperDetailPage: React.FC = () => {
  const { paperId } = useParams<{ paperId: string }>()
  const navigate = useNavigate()
  const [paper, setPaper] = useState<PaperDetail | null>(null)
  const [metrics, setMetrics] = useState<MetricSnapshot[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const loadPaperData = async () => {
      if (!paperId) {
        setError('Paper ID not provided')
        setLoading(false)
        return
      }

      setLoading(true)
      setError(null)

      try {
        const [paperData, metricsData] = await Promise.all([
          papersService.getPaperById(paperId),
          papersService.getPaperMetrics(paperId, 30),
        ])

        setPaper(paperData)
        setMetrics(metricsData.metrics)
      } catch (err) {
        console.error('Failed to load paper data:', err)
        setError('Failed to load paper details. Please try again.')
      } finally {
        setLoading(false)
      }
    }

    loadPaperData()
  }, [paperId])

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <p className="text-gray-600">Loading paper details...</p>
      </div>
    )
  }

  if (error || !paper) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600 mb-4">{error || 'Paper not found'}</p>
          <button
            onClick={() => navigate('/')}
            className="text-blue-600 hover:underline"
          >
            Back to Home
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <button
            onClick={() => navigate('/')}
            className="text-blue-600 hover:underline mb-4 inline-block"
          >
            ← Back to Home
          </button>
          <h1 className="text-3xl font-bold text-gray-900">{paper.title}</h1>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-8 space-y-6">
        {/* Authors and metadata */}
        <div className="bg-white border border-gray-200 rounded-lg p-6">
          <p className="text-gray-700 mb-4">{paper.authors.join(', ')}</p>

          <div className="flex flex-wrap gap-4 text-sm text-gray-600">
            <span>Published: {new Date(paper.published_date).toLocaleDateString()}</span>
            {paper.venue && <span>• {paper.venue}</span>}
            {paper.arxiv_id && <span>• arXiv: {paper.arxiv_id}</span>}
            {paper.doi && <span>• DOI: {paper.doi}</span>}
          </div>

          <div className="mt-4 flex gap-4">
            {paper.github_url && (
              <a
                href={paper.github_url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline"
              >
                GitHub →
              </a>
            )}
            {paper.arxiv_url && (
              <a
                href={paper.arxiv_url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline"
              >
                arXiv →
              </a>
            )}
            {paper.pdf_url && (
              <a
                href={paper.pdf_url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline"
              >
                PDF →
              </a>
            )}
          </div>
        </div>

        {/* Abstract */}
        <div className="bg-white border border-gray-200 rounded-lg p-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-3">Abstract</h2>
          <p className="text-gray-700 leading-relaxed">{paper.abstract}</p>
        </div>

        {/* Hype Score Breakdown */}
        <div className="bg-white border border-gray-200 rounded-lg p-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">Hype Score Breakdown</h2>

          <div className="space-y-4">
            <div>
              <div className="flex justify-between items-center mb-2">
                <span className="text-sm font-medium text-gray-700">Overall Hype Score</span>
                <span className="text-2xl font-bold text-blue-600">{paper.hype_score.toFixed(1)}</span>
              </div>
              <div className="w-full bg-gray-200 rounded-full h-3">
                <div
                  className="bg-blue-600 h-3 rounded-full"
                  style={{ width: `${paper.hype_score}%` }}
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4 mt-6">
              <div className="bg-gray-50 p-4 rounded">
                <p className="text-sm text-gray-600">7-Day Star Growth</p>
                <p className="text-lg font-semibold text-gray-900">
                  {(paper.star_growth_7d * 100).toFixed(1)}%
                </p>
              </div>

              <div className="bg-gray-50 p-4 rounded">
                <p className="text-sm text-gray-600">30-Day Citation Growth</p>
                <p className="text-lg font-semibold text-gray-900">
                  {(paper.citation_growth_30d * 100).toFixed(1)}%
                </p>
              </div>

              <div className="bg-gray-50 p-4 rounded">
                <p className="text-sm text-gray-600">Current Stars</p>
                <p className="text-lg font-semibold text-gray-900">{paper.current_stars}</p>
              </div>

              <div className="bg-gray-50 p-4 rounded">
                <p className="text-sm text-gray-600">Trend</p>
                <p className="text-lg font-semibold text-gray-900 capitalize">{paper.trend_label}</p>
              </div>
            </div>
          </div>
        </div>

        {/* Trend Chart */}
        <TrendChart metrics={metrics} />
      </main>
    </div>
  )
}

export default PaperDetailPage

// frontend/src/pages/PaperDetailPage.vue
<template>
  <div v-if="paper" class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
    <div class="mb-6">
      <h1 class="text-3xl font-bold mb-2">{{ paper.title }}</h1>
      <p class="text-gray-600">{{ paper.authors }}</p>
      <p class="text-sm text-gray-500">Published: {{ formatDate(paper.published_date) }}</p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
      <!-- Main Content -->
      <div class="md:col-span-2 space-y-6">
        <!-- Abstract -->
        <div class="bg-white shadow rounded-lg p-6">
          <h2 class="text-xl font-semibold mb-3">Abstract</h2>
          <p class="text-gray-700">{{ paper.abstract }}</p>
        </div>

        <!-- Star History Chart -->
        <div v-if="starHistory.length > 0" class="bg-white shadow rounded-lg p-6">
          <h2 class="text-xl font-semibold mb-3">Star History</h2>
          <div class="h-64">
            <canvas ref="chartCanvas"></canvas>
          </div>
        </div>

        <!-- References -->
        <div v-if="references.length > 0" class="bg-white shadow rounded-lg p-6">
          <h2 class="text-xl font-semibold mb-3">Citation Graph</h2>
          <div class="space-y-2">
            <div v-for="ref in references" :key="ref.paper_id" class="border-l-4 pl-4" :class="ref.relationship === 'cites' ? 'border-blue-500' : 'border-green-500'">
              <router-link :to="`/papers/${ref.paper_id}`" class="text-blue-600 hover:underline">
                {{ ref.title }}
              </router-link>
              <p class="text-sm text-gray-600">{{ ref.authors.join(', ') }} ({{ ref.year }})</p>
              <span class="text-xs text-gray-500">{{ ref.relationship === 'cites' ? 'Referenced by this paper' : 'Cites this paper' }}</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Sidebar -->
      <div class="space-y-6">
        <!-- Metrics -->
        <div class="bg-white shadow rounded-lg p-6">
          <h2 class="text-xl font-semibold mb-3">Metrics</h2>
          <dl class="space-y-2">
            <div>
              <dt class="text-sm text-gray-500">Citations</dt>
              <dd class="text-2xl font-bold">{{ paper.citations || 0 }}</dd>
            </div>
            <div>
              <dt class="text-sm text-gray-500">GitHub Stars</dt>
              <dd class="text-2xl font-bold">{{ paper.github_stars || 0 }}</dd>
            </div>
          </dl>
        </div>

        <!-- Hype Scores -->
        <div v-if="hypeScores" class="bg-white shadow rounded-lg p-6">
          <h2 class="text-xl font-semibold mb-3">Hype Scores</h2>
          <dl class="space-y-2">
            <div>
              <dt class="text-sm text-gray-500">Average</dt>
              <dd class="text-xl font-bold">{{ hypeScores.average_hype }}</dd>
            </div>
            <div>
              <dt class="text-sm text-gray-500">Weekly Growth</dt>
              <dd class="text-xl font-bold">{{ hypeScores.weekly_hype }}</dd>
            </div>
            <div>
              <dt class="text-sm text-gray-500">Monthly Growth</dt>
              <dd class="text-xl font-bold">{{ hypeScores.monthly_hype }}</dd>
            </div>
          </dl>
          <p class="text-xs text-gray-500 mt-4">{{ hypeScores.formula_explanation }}</p>
        </div>

        <!-- Links -->
        <div class="bg-white shadow rounded-lg p-6">
          <h2 class="text-xl font-semibold mb-3">Links</h2>
          <div class="space-y-2">
            <a v-if="paper.pdf_url" :href="paper.pdf_url" target="_blank" class="block text-blue-600 hover:underline">
              View PDF
            </a>
            <a :href="`${apiUrl}/api/v1/papers/${paper.id}/download-pdf`" target="_blank" class="block text-blue-600 hover:underline">
              Download PDF
            </a>
            <a v-if="paper.github_url" :href="paper.github_url" target="_blank" class="block text-blue-600 hover:underline">
              GitHub Repository
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import axios from 'axios'

const route = useRoute()
const apiUrl = import.meta.env.VITE_API_URL
const paper = ref<any>(null)
const starHistory = ref<any[]>([])
const hypeScores = ref<any>(null)
const references = ref<any[]>([])

async function loadPaper() {
  const paperId = route.params.id
  try {
    const [paperRes, historyRes, scoresRes, refsRes] = await Promise.all([
      axios.get(`${apiUrl}/api/v1/papers/${paperId}`),
      axios.get(`${apiUrl}/api/v1/papers/${paperId}/star-history`).catch(() => ({ data: [] })),
      axios.get(`${apiUrl}/api/v1/papers/${paperId}/hype-scores`).catch(() => ({ data: null })),
      axios.get(`${apiUrl}/api/v1/papers/${paperId}/references`).catch(() => ({ data: [] }))
    ])

    paper.value = paperRes.data
    starHistory.value = historyRes.data
    hypeScores.value = scoresRes.data
    references.value = refsRes.data
  } catch (error) {
    console.error('Failed to load paper:', error)
  }
}

function formatDate(isoString: string) {
  if (!isoString) return 'N/A'
  return new Date(isoString).toLocaleDateString()
}

onMounted(() => {
  loadPaper()
})
</script>
